config/routes.rb
Rails.application.routes.draw do
  
  namespace :admins_backoffice do
    get 'welcome/index' # rota para index do site
    resources :admins   # rota para administradores
    resources :subjects # rota para os assuntos/áreas
    resources :questions # rota para as perguntas
  end
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  
  devise_for :admins
  devise_for :users
  
  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Kaminari
  paginates_per 5
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
  
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy ]
  
  def index
    @admins = Admin.all.page(params[:page])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
      if @admin.save
        redirect_to admins_backoffice_admins_path, notice: "Administador criado com sucesso!"
      else
        render :new
      end
  end
  
  def edit
    
  end

  def update 
      if @admin.update(params_admin)
        redirect_to admins_backoffice_admins_path, notice: "Administador atualizado com sucesso!"
      else
        render :edit
      end
  end

  def destroy
      if @admin.destroy
        redirect_to admins_backoffice_admins_path, notice: "Administrador excluído com sucesso!"
      else
        render :index
      end
  end
  

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
  

  def set_admin
    @admin = Admin.find(params[:id])
  end
  

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
  

end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
 before_action :set_question, only: [:edit, :update, :destroy]
 before_action :get_subjects, only: [:new, :edit]
    def index
        @questions = Question.includes(:subject).order(:description).page(params[:page])
    end
    
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if  @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update    
    if  @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if  @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

    private

    def params_question
        params.require(:question).permit(:description, :subject_id, answers_attributes: [:id, :description, :correct, :_destroy])
    end

    def set_question
        @question = Question.find(params[:id])
    end

    def get_subjects
        @subjects = Subject.all        
    end
    
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
    
    before_action :set_subject, only: [:edit, :update, :destroy ]
    
    def index
        @subjects = Subject.all.page(params[:page])
    end

    def new
        @subject = Subject.new
    end

    def create
        @subject = Subject.new(params_subject)
        if @subject.save
            redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área criado com sucesso!"
        else
            render :new
        end
    end
    
    def edit
        
    end

    def update 
        if @subject.update(params_subject)
            redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área atualizado com sucesso!"
        else
            render :edit
        end
    end

    def destroy
        if @subject.destroy
            redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso!"
        else
            render :index
        end
    end
    

    private

    def params_subject
        params.require(:subject).permit(:description)
    end
    

    def set_subject
        @subject = Subject.find(params[:id])
    end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Set Layout
 layout :layout_by_resource
 
 
 protected
  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
    def index
    
    end

end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper

    def translate_attributes(object = nil, method = nil)
        (object && method) ?  object.model.human_attribute_name(method) : "informe os parâmetros"
        
    end
    
    def translate_model_name(object = nil, method = nil)
       (object && method) ? object.model_name.human(method) : "erro"
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested-fields">
<%= f.label :description %><br>
<%= f.text_field :description %>
<%= f.check_box :correct %> Correta?

<%= link_to_remove_association('Remover', f) %>
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form', locals: {action_message: 'Editando '} %>

app/views/admins_backoffice/questions/index.html.erb
<h1><%= translate_model_name(@questions, count: 2) %> </h1>

<div class="card shadow mb-4">
    
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary"><%= t('message.listing', model: translate_model_name(@questions, count: 2)) %>
            <%= link_to new_admins_backoffice_question_path, class:'btn btn-outline-success' do %>
                <i>Adicionar novo</i>
            <% end %> 
        </h6>
        
    </div>
    <div class="card-body">
        <div class="table-responsive" >
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-10 col-md-12">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                <thead>
                    <tr role="row">
                        <th rowspan="1" colspan="1"><%= translate_attributes(@questions, :id) %></th>
                        <th rowspan="1" colspan="1"><%= translate_attributes(@questions, :description) %></th>
                        <th rowspan="1" colspan="1"><%= translate_attributes(@questions, :subject) %></th>
                        <th rowspan="1" colspan="1">Editar</th>
                        <th rowspan="1" colspan="1">Visualizar</th>
                        <th rowspan="1" colspan="1">Apagar</th>
                        
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th rowspan="1" colspan="1"><%= translate_attributes(@questions, :id) %></th>
                        <th rowspan="1" colspan="1"><%= translate_attributes(@questions, :description) %></th>
                        <th rowspan="1" colspan="1"><%= translate_attributes(@questions, :subject) %></th>
                        <th rowspan="1" colspan="1">Editar</th>
                        <th rowspan="1" colspan="1">Visualizar</th>
                        <th rowspan="1" colspan="1">Apagar</th>
                </tfoot>
                <tbody>
                    <% @questions.each do |question| %>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><%= question.id %></td>
                        <td><%= question.description.truncate(50) %></td>
                        <td><%= question.subject.description %></td>
                        <td style="width: 100px;">
                              <%= link_to edit_admins_backoffice_question_path(question), class:'btn btn-success btn-circle btn-sm' do %>
                            
                              <i class="fas fa-check"></i>
                            <% end %>
                            </td>
                        
                        <td style="width: 100px;"><button class="btn btn-info btn-circle btn-sm"  ><i class="fas fa-info-circle"></i></button></td>
                        <td style="width: 100px;">
                        <%= link_to admins_backoffice_question_path(question), method: :delete, class:'btn btn-danger btn-circle btn-sm', data: { confirm: 'Deseja excluir o registro?' } do %>
                            
                              <i class="fas fa-trash"></i>
                            <% end %>
                        </td>
                    </tr>    
                    <% end %>
                    
                </tbody>
                
            </table>
        </div>
    </div>
    <%= paginate @questions %>
   
</div>
</div>
        </div>
    </div>
</div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form', locals: {action_message: 'Novo '} %>

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: {action_message: 'Editando '} %>

app/views/admins_backoffice/subjects/index.html.erb
<h1><%= translate_model_name(@subjects, count: 2) %> </h1>

<div class="card shadow mb-4">
    
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary"><%= t('message.listing', model: translate_model_name(@subjects, count: 2)) %>
            <%= link_to new_admins_backoffice_subject_path, class:'btn btn-outline-success' do %>
                <i>Adicionar novo</i>
            <% end %> 
        </h6>
        
    </div>
    <div class="card-body">
        <div class="table-responsive" >
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-10 col-md-12">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                <thead>
                    <tr role="row">
                        <th rowspan="1" colspan="1">
                            <%= translate_attributes(@subjects, :id) %>
                        </th>
                        <th rowspan="1" colspan="1">
                            <%= translate_attributes(@subjects, :description) %>
                        </th>
                        <th rowspan="1" colspan="1">Editar</th>
                        <th rowspan="1" colspan="1">Visualizar</th>
                        <th rowspan="1" colspan="1">Apagar</th>
                        
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th rowspan="1" colspan="1">
                            <%= translate_attributes(@subjects, :id) %>
                        </th>
                        <th rowspan="1" colspan="1">
                            <%= translate_attributes(@subjects, :description) %>
                        </th>
                        <th rowspan="1" colspan="1">Editar</th>
                        <th rowspan="1" colspan="1">Visualizar</th>
                        <th rowspan="1" colspan="1">Apagar</th>
                </tfoot>
                <tbody>
                    <% @subjects.each do |subject| %>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><%= subject.id %></td>
                        <td><%= subject.description %></td>
                        <td style="width: 100px;">
                              <%= link_to edit_admins_backoffice_subject_path(subject), class:'btn btn-success btn-circle btn-sm' do %>
                            
                              <i class="fas fa-check"></i>
                            <% end %>
                            </td>
                        
                        <td style="width: 100px;"><button class="btn btn-info btn-circle btn-sm"  ><i class="fas fa-info-circle"></i></button></td>
                        <td style="width: 100px;">
                        <%= link_to admins_backoffice_subject_path(subject), method: :delete, class:'btn btn-danger btn-circle btn-sm', data: { confirm: 'Deseja excluir o registro?' } do %>
                            
                              <i class="fas fa-trash"></i>
                            <% end %>
                        </td>
                    </tr>    
                    <% end %>
                    
                </tbody>
                
            </table>
        </div>
    </div>
    <%= paginate @subjects %>
   
</div>
</div>
        </div>
    </div>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form', locals: {action_message: 'Novo '} %>

app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>